-- Resources change shape (SPEC-001). No production database exists yet: local and demo data
-- are regenerated by the seed, so existing rows are cleared rather than converted.
TRUNCATE TABLE "resource_booking", "resource";
