// Embeds the SQL migrations in a module, so they can be applied where there is no file system
// (the demo's service worker). Run after `drizzle-kit generate`; the output is not committed.
import { readFileSync, writeFileSync } from 'node:fs';

const folder = new URL('../migrations/', import.meta.url);
const journal = JSON.parse(readFileSync(new URL('meta/_journal.json', folder), 'utf8')) as {
  entries: { tag: string }[];
};

const migrations = journal.entries.map(({ tag }) => ({
  name: tag,
  statements: readFileSync(new URL(`${tag}.sql`, folder), 'utf8')
    .split('--> statement-breakpoint')
    .map((statement) => statement.trim())
    .filter((statement) => statement.length > 0),
}));

writeFileSync(
  new URL('../src/migrations.gen.ts', import.meta.url),
  `// Generated by scripts/embed-migrations.ts from migrations/. Do not edit.\n` +
    `export const migrations: { name: string; statements: string[] }[] = ${JSON.stringify(migrations, null, 2)};\n`,
);
